# Application Information
appName: "validation-service-are"
appNamespace: "${namespace}" # defaults to Release.Namespace
# Settings for the Kubernetes Service Object for the Application
appServiceType: ClusterIP
appServicePortExternal: 8080
appServicePortTarget: 8080
appServicePortProtocol: TCP
appServicePortName: http

# HTTP Rules for internal endpoints - https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPRoute
virtualServiceHttpRules:
  - match:
      - uri:
          prefix: /
    rewrite:
      uri: /